import { normalize } from './textNormalize'

/**
 * allrugby.com profile pages report nationality as a French country name (JSON-LD
 * `"nationality"` field, e.g. "Afrique du sud", "Nouvelle-Zélande") — not an ISO code,
 * and not always their own flag-image code either (e.g. South Africa's flag image is
 * "afs.png", not the ISO alpha-3 "ZAF"). This maps those French country names to ISO
 * alpha-2 codes, aiming to cover every nation a player could plausibly be tagged with
 * (not just common rugby nations), so imports spanning many countries/competitions
 * don't leave nationality unresolved. Keys are written as natural French country names
 * and normalized (accent-stripped, lowercased) at load time via `normalize`, matching
 * how lookups are normalized — so add new entries in readable French, not pre-normalized form.
 *
 * Note: allrugby's own tagging isn't always nation-accurate within the UK — a Welsh
 * player (Will Rowlands) was seen tagged "Angleterre" — so treat GB-ENG/GB-SCT/GB-WLS/
 * GB-NIR here as best-effort, not authoritative.
 */
const RAW_FRENCH_COUNTRY_TO_ALPHA2: Record<string, string> = {
  // Western Europe
  France: 'FR',
  Angleterre: 'GB-ENG',
  Écosse: 'GB-SCT',
  'Pays de Galles': 'GB-WLS',
  'Irlande du Nord': 'GB-NIR',
  'Royaume-Uni': 'GB',
  Irlande: 'IE',
  Italie: 'IT',
  Espagne: 'ES',
  Portugal: 'PT',
  Allemagne: 'DE',
  Belgique: 'BE',
  'Pays-Bas': 'NL',
  Luxembourg: 'LU',
  Suisse: 'CH',
  Autriche: 'AT',
  Andorre: 'AD',
  Monaco: 'MC',
  Malte: 'MT',
  Liechtenstein: 'LI',
  // Northern Europe
  Suède: 'SE',
  Norvège: 'NO',
  Danemark: 'DK',
  Finlande: 'FI',
  Islande: 'IS',
  // Eastern / Central Europe
  Géorgie: 'GE',
  Roumanie: 'RO',
  Russie: 'RU',
  Ukraine: 'UA',
  Pologne: 'PL',
  'République tchèque': 'CZ',
  Tchéquie: 'CZ',
  Tchécoslovaquie: 'CZ',
  Slovaquie: 'SK',
  Hongrie: 'HU',
  Croatie: 'HR',
  Serbie: 'RS',
  Slovénie: 'SI',
  Bulgarie: 'BG',
  Grèce: 'GR',
  Chypre: 'CY',
  Moldavie: 'MD',
  Biélorussie: 'BY',
  Lituanie: 'LT',
  Lettonie: 'LV',
  Estonie: 'EE',
  'Bosnie-Herzégovine': 'BA',
  'Macédoine du Nord': 'MK',
  Monténégro: 'ME',
  Albanie: 'AL',
  Arménie: 'AM',
  Azerbaïdjan: 'AZ',
  Kazakhstan: 'KZ',
  Kosovo: 'XK',
  // Africa
  'Afrique du Sud': 'ZA',
  Namibie: 'NA',
  Zimbabwe: 'ZW',
  Kenya: 'KE',
  Ouganda: 'UG',
  Maroc: 'MA',
  Algérie: 'DZ',
  Tunisie: 'TN',
  Libye: 'LY',
  Égypte: 'EG',
  "Côte d'Ivoire": 'CI',
  Madagascar: 'MG',
  Sénégal: 'SN',
  Cameroun: 'CM',
  Congo: 'CG',
  'République démocratique du Congo': 'CD',
  Nigéria: 'NG',
  Ghana: 'GH',
  Zambie: 'ZM',
  Botswana: 'BW',
  Tanzanie: 'TZ',
  Rwanda: 'RW',
  Burundi: 'BI',
  Mali: 'ML',
  'Burkina Faso': 'BF',
  Togo: 'TG',
  Bénin: 'BJ',
  Gabon: 'GA',
  Guinée: 'GN',
  Angola: 'AO',
  Mozambique: 'MZ',
  Eswatini: 'SZ',
  Lesotho: 'LS',
  Comores: 'KM',
  Maurice: 'MU',
  Seychelles: 'SC',
  'République centrafricaine': 'CF',
  Tchad: 'TD',
  Niger: 'NE',
  'Guinée-Bissau': 'GW',
  'Guinée équatoriale': 'GQ',
  'Cap-Vert': 'CV',
  Gambie: 'GM',
  'Sierra Leone': 'SL',
  Liberia: 'LR',
  Mauritanie: 'MR',
  Soudan: 'SD',
  'Soudan du Sud': 'SS',
  Éthiopie: 'ET',
  Somalie: 'SO',
  Djibouti: 'DJ',
  'Sahara occidental': 'EH',
  // Americas
  Argentine: 'AR',
  Uruguay: 'UY',
  Chili: 'CL',
  Brésil: 'BR',
  Canada: 'CA',
  'États-Unis': 'US',
  Mexique: 'MX',
  Paraguay: 'PY',
  Colombie: 'CO',
  Pérou: 'PE',
  Venezuela: 'VE',
  Équateur: 'EC',
  Bolivie: 'BO',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Guatemala: 'GT',
  Honduras: 'HN',
  Nicaragua: 'NI',
  Salvador: 'SV',
  Cuba: 'CU',
  'République dominicaine': 'DO',
  Jamaïque: 'JM',
  'Trinité-et-Tobago': 'TT',
  Bahamas: 'BS',
  Barbade: 'BB',
  Guyana: 'GY',
  Suriname: 'SR',
  Guyane: 'GF',
  Martinique: 'MQ',
  Guadeloupe: 'GP',
  // Asia / Middle East
  Japon: 'JP',
  'Corée du Sud': 'KR',
  'Corée du Nord': 'KP',
  Chine: 'CN',
  'Hong Kong': 'HK',
  Taïwan: 'TW',
  Philippines: 'PH',
  Singapour: 'SG',
  Malaisie: 'MY',
  Thaïlande: 'TH',
  Indonésie: 'ID',
  'Sri Lanka': 'LK',
  Inde: 'IN',
  Pakistan: 'PK',
  Bangladesh: 'BD',
  'Émirats arabes unis': 'AE',
  'Arabie saoudite': 'SA',
  Qatar: 'QA',
  Koweït: 'KW',
  Bahreïn: 'BH',
  Oman: 'OM',
  Israël: 'IL',
  Palestine: 'PS',
  Liban: 'LB',
  Jordanie: 'JO',
  Turquie: 'TR',
  Iran: 'IR',
  // Oceania / Pacific
  Australie: 'AU',
  'Nouvelle-Zélande': 'NZ',
  Fidji: 'FJ',
  Tonga: 'TO',
  Samoa: 'WS',
  'Samoa américaines': 'AS',
  'Papouasie-Nouvelle-Guinée': 'PG',
  Vanuatu: 'VU',
  'Îles Cook': 'CK',
  Niue: 'NU',
  Tuvalu: 'TV',
  Kiribati: 'KI',
  'Nouvelle-Calédonie': 'NC',
  'Polynésie française': 'PF',
  'Wallis-et-Futuna': 'WF',
  Guam: 'GU',
  'Îles Salomon': 'SB',
}

const FRENCH_COUNTRY_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_FRENCH_COUNTRY_TO_ALPHA2).map(([name, code]) => [normalize(name), code]),
)

/** Maps a raw French country name (as reported on an allrugby.com profile) to an ISO alpha-2 code, or null if unrecognized. */
export function alpha2ForFrenchCountryName(raw: string): string | null {
  return FRENCH_COUNTRY_TO_ALPHA2[normalize(raw)] ?? null
}

/**
 * all.rugby profile pages report nationality as an English country name (JSON-LD
 * `"nationality"` field, e.g. "South Africa") — same @graph/Person shape as
 * allrugby.com's JSON-LD, just English-language. Same best-effort caveat as the
 * French map above: nation tagging within the UK isn't always accurate.
 *
 * The Transfermarkt football dataset reports `country_of_citizenship` in the same
 * shape, so it shares this map — see the Transfermarkt-spelling block at the end.
 */
const RAW_ENGLISH_COUNTRY_TO_ALPHA2: Record<string, string> = {
  // Western Europe
  France: 'FR',
  England: 'GB-ENG',
  Scotland: 'GB-SCT',
  Wales: 'GB-WLS',
  'Northern Ireland': 'GB-NIR',
  'United Kingdom': 'GB',
  Ireland: 'IE',
  Italy: 'IT',
  Spain: 'ES',
  Portugal: 'PT',
  Germany: 'DE',
  Belgium: 'BE',
  Netherlands: 'NL',
  Luxembourg: 'LU',
  Switzerland: 'CH',
  Austria: 'AT',
  Andorra: 'AD',
  Monaco: 'MC',
  Malta: 'MT',
  Liechtenstein: 'LI',
  // Northern Europe
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
  Finland: 'FI',
  Iceland: 'IS',
  // Eastern / Central Europe
  Georgia: 'GE',
  Romania: 'RO',
  Russia: 'RU',
  Ukraine: 'UA',
  Poland: 'PL',
  'Czech Republic': 'CZ',
  Czechia: 'CZ',
  Slovakia: 'SK',
  Hungary: 'HU',
  Croatia: 'HR',
  Serbia: 'RS',
  Slovenia: 'SI',
  Bulgaria: 'BG',
  Greece: 'GR',
  Cyprus: 'CY',
  Moldova: 'MD',
  Belarus: 'BY',
  Lithuania: 'LT',
  Latvia: 'LV',
  Estonia: 'EE',
  'Bosnia and Herzegovina': 'BA',
  'North Macedonia': 'MK',
  Montenegro: 'ME',
  Albania: 'AL',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
  Kazakhstan: 'KZ',
  Kosovo: 'XK',
  // Africa
  'South Africa': 'ZA',
  Namibia: 'NA',
  Zimbabwe: 'ZW',
  Kenya: 'KE',
  Uganda: 'UG',
  Morocco: 'MA',
  Algeria: 'DZ',
  Tunisia: 'TN',
  Libya: 'LY',
  Egypt: 'EG',
  'Ivory Coast': 'CI',
  "Cote d'Ivoire": 'CI',
  Madagascar: 'MG',
  Senegal: 'SN',
  Cameroon: 'CM',
  Congo: 'CG',
  'Democratic Republic of the Congo': 'CD',
  Nigeria: 'NG',
  Ghana: 'GH',
  Zambia: 'ZM',
  Botswana: 'BW',
  Tanzania: 'TZ',
  Rwanda: 'RW',
  Burundi: 'BI',
  Mali: 'ML',
  'Burkina Faso': 'BF',
  Togo: 'TG',
  Benin: 'BJ',
  Gabon: 'GA',
  Guinea: 'GN',
  Angola: 'AO',
  Mozambique: 'MZ',
  Eswatini: 'SZ',
  Lesotho: 'LS',
  Comoros: 'KM',
  Mauritius: 'MU',
  Seychelles: 'SC',
  'Central African Republic': 'CF',
  Chad: 'TD',
  Niger: 'NE',
  'Guinea-Bissau': 'GW',
  'Equatorial Guinea': 'GQ',
  'Cape Verde': 'CV',
  Gambia: 'GM',
  'Sierra Leone': 'SL',
  Liberia: 'LR',
  Mauritania: 'MR',
  Sudan: 'SD',
  'South Sudan': 'SS',
  Ethiopia: 'ET',
  Somalia: 'SO',
  Djibouti: 'DJ',
  'Western Sahara': 'EH',
  // Americas
  Argentina: 'AR',
  Uruguay: 'UY',
  Chile: 'CL',
  Brazil: 'BR',
  Canada: 'CA',
  'United States': 'US',
  Mexico: 'MX',
  Paraguay: 'PY',
  Colombia: 'CO',
  Peru: 'PE',
  Venezuela: 'VE',
  Ecuador: 'EC',
  Bolivia: 'BO',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Guatemala: 'GT',
  Honduras: 'HN',
  Nicaragua: 'NI',
  'El Salvador': 'SV',
  Cuba: 'CU',
  'Dominican Republic': 'DO',
  Jamaica: 'JM',
  'Trinidad and Tobago': 'TT',
  Bahamas: 'BS',
  Barbados: 'BB',
  Guyana: 'GY',
  Suriname: 'SR',
  'French Guiana': 'GF',
  Martinique: 'MQ',
  Guadeloupe: 'GP',
  // Asia / Middle East
  Japan: 'JP',
  'South Korea': 'KR',
  'North Korea': 'KP',
  China: 'CN',
  'Hong Kong': 'HK',
  Taiwan: 'TW',
  Philippines: 'PH',
  Singapore: 'SG',
  Malaysia: 'MY',
  Thailand: 'TH',
  Indonesia: 'ID',
  'Sri Lanka': 'LK',
  India: 'IN',
  Pakistan: 'PK',
  Bangladesh: 'BD',
  'United Arab Emirates': 'AE',
  'Saudi Arabia': 'SA',
  Qatar: 'QA',
  Kuwait: 'KW',
  Bahrain: 'BH',
  Oman: 'OM',
  Israel: 'IL',
  Palestine: 'PS',
  Lebanon: 'LB',
  Jordan: 'JO',
  Turkey: 'TR',
  Iran: 'IR',
  // Oceania / Pacific
  Australia: 'AU',
  'New Zealand': 'NZ',
  Fiji: 'FJ',
  Tonga: 'TO',
  Samoa: 'WS',
  'American Samoa': 'AS',
  'Papua New Guinea': 'PG',
  Vanuatu: 'VU',
  'Cook Islands': 'CK',
  Niue: 'NU',
  Tuvalu: 'TV',
  Kiribati: 'KI',
  'New Caledonia': 'NC',
  'French Polynesia': 'PF',
  'Wallis and Futuna': 'WF',
  Guam: 'GU',
  'Solomon Islands': 'SB',

  // Transfermarkt spellings (players.country_of_citizenship). Mostly alternative names
  // for countries already listed above — kept as separate keys rather than renaming the
  // existing ones, so both sources keep resolving. A few are not English at all
  // ("Neukaledonien", "St. Vincent & Grenadinen"), which is how Transfermarkt ships them.
  Afghanistan: 'AF',
  'Antigua and Barbuda': 'AG',
  Aruba: 'AW',
  Belize: 'BZ',
  Bermuda: 'BM',
  Bhutan: 'BT',
  Bonaire: 'BQ',
  'Bosnia-Herzegovina': 'BA',
  'Brunei Darussalam': 'BN',
  Cambodia: 'KH',
  'Chinese Taipei': 'TW',
  Curacao: 'CW',
  'DR Congo': 'CD',
  Eritrea: 'ER',
  'Faroe Islands': 'FO',
  Gibraltar: 'GI',
  Grenada: 'GD',
  Haiti: 'HT',
  Hongkong: 'HK',
  Iraq: 'IQ',
  'Korea, North': 'KP',
  'Korea, South': 'KR',
  Kyrgyzstan: 'KG',
  Laos: 'LA',
  Macao: 'MO',
  Malawi: 'MW',
  Maldives: 'MV',
  Mongolia: 'MN',
  Montserrat: 'MS',
  Myanmar: 'MM',
  Neukaledonien: 'NC',
  'Puerto Rico': 'PR',
  Réunion: 'RE',
  'Saint-Martin': 'MF',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Sint Maarten': 'SX',
  'Southern Sudan': 'SS',
  'St. Kitts & Nevis': 'KN',
  'St. Lucia': 'LC',
  'St. Vincent & Grenadinen': 'VC',
  Syria: 'SY',
  Tahiti: 'PF',
  Tajikistan: 'TJ',
  'The Gambia': 'GM',
  'Timor-Leste': 'TL',
  Turkmenistan: 'TM',
  Türkiye: 'TR',
  Uzbekistan: 'UZ',
  Vietnam: 'VN',
  Yemen: 'YE',
}

const ENGLISH_COUNTRY_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_ENGLISH_COUNTRY_TO_ALPHA2).map(([name, code]) => [normalize(name), code]),
)

/** Maps a raw English country name (as reported on an all.rugby profile) to an ISO alpha-2 code, or null if unrecognized. */
export function alpha2ForEnglishCountryName(raw: string): string | null {
  return ENGLISH_COUNTRY_TO_ALPHA2[normalize(raw)] ?? null
}
