import { normalize } from './textNormalize';

/**
 * allrugby.com profile pages report nationality as a French country name (JSON-LD
 * `"nationality"` field, e.g. "Afrique du sud", "Nouvelle-Zélande") — not an ISO code,
 * and not always their own flag-image code either (e.g. South Africa's flag image is
 * "afs.png", not the ISO alpha-3 "ZAF"). This maps those French country names to ISO
 * alpha-2 codes, aiming to cover every nation a player could plausibly be tagged with
 * (not just common rugby nations), so imports spanning many countries/competitions
 * don't leave nationality unresolved. Keys are written as natural French country names
 * and normalized (accent-stripped, lowercased) at load time via `normalize`, matching
 * how lookups are normalized — so add new entries in readable French, not pre-normalized form.
 *
 * Note: allrugby's own tagging isn't always nation-accurate within the UK — a Welsh
 * player (Will Rowlands) was seen tagged "Angleterre" — so treat GB-ENG/GB-SCT/GB-WLS/
 * GB-NIR here as best-effort, not authoritative.
 */
const RAW_FRENCH_COUNTRY_TO_ALPHA2: Record<string, string> = {
  // Western Europe
  France: 'FR',
  Angleterre: 'GB-ENG',
  Écosse: 'GB-SCT',
  'Pays de Galles': 'GB-WLS',
  'Irlande du Nord': 'GB-NIR',
  'Royaume-Uni': 'GB',
  Irlande: 'IE',
  Italie: 'IT',
  Espagne: 'ES',
  Portugal: 'PT',
  Allemagne: 'DE',
  Belgique: 'BE',
  'Pays-Bas': 'NL',
  Luxembourg: 'LU',
  Suisse: 'CH',
  Autriche: 'AT',
  Andorre: 'AD',
  Monaco: 'MC',
  Malte: 'MT',
  Liechtenstein: 'LI',
  // Northern Europe
  Suède: 'SE',
  Norvège: 'NO',
  Danemark: 'DK',
  Finlande: 'FI',
  Islande: 'IS',
  // Eastern / Central Europe
  Géorgie: 'GE',
  Roumanie: 'RO',
  Russie: 'RU',
  Ukraine: 'UA',
  Pologne: 'PL',
  'République tchèque': 'CZ',
  Tchéquie: 'CZ',
  Tchécoslovaquie: 'CZ',
  Slovaquie: 'SK',
  Hongrie: 'HU',
  Croatie: 'HR',
  Serbie: 'RS',
  Slovénie: 'SI',
  Bulgarie: 'BG',
  Grèce: 'GR',
  Chypre: 'CY',
  Moldavie: 'MD',
  Biélorussie: 'BY',
  Lituanie: 'LT',
  Lettonie: 'LV',
  Estonie: 'EE',
  'Bosnie-Herzégovine': 'BA',
  'Macédoine du Nord': 'MK',
  Monténégro: 'ME',
  Albanie: 'AL',
  Arménie: 'AM',
  Azerbaïdjan: 'AZ',
  Kazakhstan: 'KZ',
  Kosovo: 'XK',
  // Africa
  'Afrique du Sud': 'ZA',
  Namibie: 'NA',
  Zimbabwe: 'ZW',
  Kenya: 'KE',
  Ouganda: 'UG',
  Maroc: 'MA',
  Algérie: 'DZ',
  Tunisie: 'TN',
  Libye: 'LY',
  Égypte: 'EG',
  "Côte d'Ivoire": 'CI',
  Madagascar: 'MG',
  Sénégal: 'SN',
  Cameroun: 'CM',
  Congo: 'CG',
  'République démocratique du Congo': 'CD',
  Nigéria: 'NG',
  Ghana: 'GH',
  Zambie: 'ZM',
  Botswana: 'BW',
  Tanzanie: 'TZ',
  Rwanda: 'RW',
  Burundi: 'BI',
  Mali: 'ML',
  'Burkina Faso': 'BF',
  Togo: 'TG',
  Bénin: 'BJ',
  Gabon: 'GA',
  Guinée: 'GN',
  Angola: 'AO',
  Mozambique: 'MZ',
  Eswatini: 'SZ',
  Lesotho: 'LS',
  Comores: 'KM',
  Maurice: 'MU',
  Seychelles: 'SC',
  'République centrafricaine': 'CF',
  Tchad: 'TD',
  Niger: 'NE',
  'Guinée-Bissau': 'GW',
  'Guinée équatoriale': 'GQ',
  'Cap-Vert': 'CV',
  Gambie: 'GM',
  'Sierra Leone': 'SL',
  Liberia: 'LR',
  Mauritanie: 'MR',
  Soudan: 'SD',
  'Soudan du Sud': 'SS',
  Éthiopie: 'ET',
  Somalie: 'SO',
  Djibouti: 'DJ',
  'Sahara occidental': 'EH',
  // Americas
  Argentine: 'AR',
  Uruguay: 'UY',
  Chili: 'CL',
  Brésil: 'BR',
  Canada: 'CA',
  'États-Unis': 'US',
  Mexique: 'MX',
  Paraguay: 'PY',
  Colombie: 'CO',
  Pérou: 'PE',
  Venezuela: 'VE',
  Équateur: 'EC',
  Bolivie: 'BO',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Guatemala: 'GT',
  Honduras: 'HN',
  Nicaragua: 'NI',
  Salvador: 'SV',
  Cuba: 'CU',
  'République dominicaine': 'DO',
  Jamaïque: 'JM',
  'Trinité-et-Tobago': 'TT',
  Bahamas: 'BS',
  Barbade: 'BB',
  Guyana: 'GY',
  Suriname: 'SR',
  Guyane: 'GF',
  Martinique: 'MQ',
  Guadeloupe: 'GP',
  // Asia / Middle East
  Japon: 'JP',
  'Corée du Sud': 'KR',
  'Corée du Nord': 'KP',
  Chine: 'CN',
  'Hong Kong': 'HK',
  Taïwan: 'TW',
  Philippines: 'PH',
  Singapour: 'SG',
  Malaisie: 'MY',
  Thaïlande: 'TH',
  Indonésie: 'ID',
  'Sri Lanka': 'LK',
  Inde: 'IN',
  Pakistan: 'PK',
  Bangladesh: 'BD',
  'Émirats arabes unis': 'AE',
  'Arabie saoudite': 'SA',
  Qatar: 'QA',
  Koweït: 'KW',
  Bahreïn: 'BH',
  Oman: 'OM',
  Israël: 'IL',
  Palestine: 'PS',
  Liban: 'LB',
  Jordanie: 'JO',
  Turquie: 'TR',
  Iran: 'IR',
  // Oceania / Pacific
  Australie: 'AU',
  'Nouvelle-Zélande': 'NZ',
  Fidji: 'FJ',
  Tonga: 'TO',
  Samoa: 'WS',
  'Samoa américaines': 'AS',
  'Papouasie-Nouvelle-Guinée': 'PG',
  Vanuatu: 'VU',
  'Îles Cook': 'CK',
  Niue: 'NU',
  Tuvalu: 'TV',
  Kiribati: 'KI',
  'Nouvelle-Calédonie': 'NC',
  'Polynésie française': 'PF',
  'Wallis-et-Futuna': 'WF',
  Guam: 'GU',
  'Îles Salomon': 'SB',
};

const FRENCH_COUNTRY_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_FRENCH_COUNTRY_TO_ALPHA2).map(([name, code]) => [
    normalize(name),
    code,
  ]),
);

/** Maps a raw French country name (as reported on an allrugby.com profile) to an ISO alpha-2 code, or null if unrecognized. */
export function alpha2ForFrenchCountryName(raw: string): string | null {
  return FRENCH_COUNTRY_TO_ALPHA2[normalize(raw)] ?? null;
}
